name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, '*-openal-*' ]
  pull_request:
    branches: [ main, develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cmake_generator: "Unix Makefiles"
            build_tool: "make"
          - os: windows-latest
            cmake_generator: "Visual Studio 17 2022"
            build_tool: "cmake"
          - os: macos-latest
            cmake_generator: "Unix Makefiles"
            build_tool: "make"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          libxext-dev \
          libx11-dev \
          mesa-common-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libopenal-dev \
          pkg-config
        # Verify OpenAL installation
        pkg-config --exists openal && echo "OpenAL found via pkg-config" || echo "OpenAL not found via pkg-config"
        ls -la /usr/lib/*/libopenal* || ls -la /usr/lib/libopenal* || echo "OpenAL library files not found"

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Install OpenAL and required dependencies
        brew update
        brew install openal-soft pkg-config
        # Verify installation
        ls -la /opt/homebrew/lib/libopenal* || ls -la /usr/local/lib/libopenal* || echo "OpenAL not found in expected locations"

    - name: Setup vcpkg (Windows)
      if: matrix.os == 'windows-latest'
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: '2024.11.16'
        vcpkgJsonGlob: 'vcpkg.json'
        appendedCacheKey: 'openal-audio'

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # OpenAL installed via vcpkg above
        echo "Windows OpenAL dependencies handled by vcpkg"

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Debug source files (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        echo "=== Source File Debug Information ==="
        echo "Current working directory: $(pwd)"
        echo "Date: $(date)"
        echo ""
        echo "=== Directory Structure Check ==="
        echo "src/ directory exists: $(test -d src && echo 'YES' || echo 'NO')"
        echo "src/core/ directory exists: $(test -d src/core && echo 'YES' || echo 'NO')"
        echo "src/scene/ directory exists: $(test -d src/scene && echo 'YES' || echo 'NO')"
        echo ""
        echo "=== Core Source Files Check ==="
        for file in "src/core/Logger.cpp" "src/core/Entity.cpp" "src/core/EntityTypes.cpp" "src/core/Transform.cpp"; do
            if [ -f "$file" ]; then
                echo "✓ $file exists ($(wc -l < "$file") lines)"
            else
                echo "✗ $file MISSING"
            fi
        done
        echo ""
        echo "=== Git Status ==="
        git status --porcelain
        echo ""
        echo "=== Recent Commits ==="
        git log --oneline -3
        echo ""

    - name: Configure CMake (Unix)
      if: matrix.os != 'windows-latest'
      working-directory: ${{github.workspace}}/build
      run: |
        echo "=== CMake Configuration Debug ==="
        echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
        pkg-config --exists openal && echo "pkg-config found OpenAL" || echo "pkg-config did NOT find OpenAL"
        echo ""
        cmake .. \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -G "${{ matrix.cmake_generator }}"

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}/build
      run: |
        echo "=== Windows CMake Configuration Debug ==="
        echo "VCPKG_ROOT: $env:VCPKG_ROOT"
        echo "Checking vcpkg toolchain file..."
        if (Test-Path "${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake") {
          echo "vcpkg toolchain file found"
        } else {
          echo "vcpkg toolchain file NOT found"
        }
        echo ""
        cmake .. -G "${{ matrix.cmake_generator }}" -A x64 -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build project (Unix)
      if: matrix.os != 'windows-latest'
      working-directory: ${{github.workspace}}/build
      run: ${{ matrix.build_tool }} -j$(nproc 2>/dev/null || echo 4)

    - name: Build project (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $env:BUILD_TYPE --parallel

    - name: Test build output (Unix)
      if: matrix.os != 'windows-latest'
      working-directory: ${{github.workspace}}/build
      run: |
        if [ -f "./IKore" ]; then
          echo "✅ Build successful - IKore executable created"
          ls -la ./IKore
        else
          echo "❌ Build failed - IKore executable not found"
          exit 1
        fi

    - name: Test build output (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}/build
      shell: cmd
      run: |
        if exist "Release\IKore.exe" (
          echo ✅ Build successful - IKore.exe created
          dir Release\IKore.exe
        ) else (
          echo ❌ Build failed - IKore.exe not found
          exit /b 1
        )

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: IKore-${{ matrix.os }}-${{ github.sha }}
        path: |
          ${{ github.workspace }}/build/IKore*
          ${{ github.workspace }}/build/Release/IKore*
        retention-days: 7

  lint-and-format:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check code formatting
      run: |
        echo "🔍 Checking code formatting..."
        # For now, just check if files exist and are properly structured
        find src/ -name "*.cpp" -o -name "*.h" | while read file; do
          if [ -s "$file" ]; then
            echo "✅ $file exists and is not empty"
          else
            echo "❌ $file is empty or missing"
            exit 1
          fi
        done

    - name: Check CMakeLists.txt
      run: |
        echo "🔍 Checking CMakeLists.txt..."
        if [ -f "CMakeLists.txt" ]; then
          echo "✅ CMakeLists.txt exists"
          # Check for required components
          if grep -q "project(IKoreEngine" CMakeLists.txt; then
            echo "✅ Project name is correctly set"
          else
            echo "❌ Project name not found or incorrect"
            exit 1
          fi
        else
          echo "❌ CMakeLists.txt not found"
          exit 1
        fi

  build-status:
    name: Build Status
    runs-on: ubuntu-latest
    needs: [build, lint-and-format]
    if: always()
    
    steps:
    - name: Report build status
      run: |
        if [ "${{ needs.build.result }}" == "success" ] && [ "${{ needs.lint-and-format.result }}" == "success" ]; then
          echo "🎉 All builds and checks passed successfully!"
        else
          echo "❌ Some builds or checks failed:"
          echo "Build result: ${{ needs.build.result }}"
          echo "Lint result: ${{ needs.lint-and-format.result }}"
          exit 1
        fi
